s/\bm2a\b/matchesEncoded/g
s/\bm3a\b/matchesKey/g
s/\bm4a\b/equalsObj/g
s/\bm5b\b/getDomain/g
s/\bm7b\b/concatKey/g
s/\bm8a\b/concatKeyObj/g
s/\bm10a\b/listRecordStores/g
s/\bm16a\b/getTextBoxString/g
s/\bm18a\b/createContactInfoCmd/g
s/\bm19b\b/initTileCache/g
s/\bm20a\b/getTileImage/g
s/\bm21k\b/pruneStaleRequests/g
s/\bm22c\b/tileLoaderLoop/g
s/\bm23a\b/cacheTileImage/g
s/\bm24d\b/clearSatelliteTiles/g
s/\bm25l\b/getTileCache/g
s/\bm26m\b/createRegionVector/g
s/\bm27a\b/addXmlChildTexts/g
s/\bm28b\b/getXmlText/g
s/\bm29e\b/showRegionSelector/g
s/\bm30f\b/resetRegForm/g
s/\bm31a\b/updateRegDropdowns/g
s/\bm32g\b/buildRegData/g
s/\bm33b\b/intToStringPositive/g
s/\bm35c\b/parseVersionByte/g
s/\bm36n\b/formatVersion/g
s/\bm38d\b/setOrGenerateGuid/g
s/\bm39e\b/validateGuid/g
s/\bm41j\b/initGeoRegions/g
s/\bm42a\b/addGeoRegion/g
s/\bm43a\b/isInSavedRegion/g
s/\bm44a\b/parseGeoConfig/g
