# Phase 7b: AppController methods m355-m427 (73)

s/\bm355x\b/processBackgroundTasks/g
s/\bm356y\b/markScreenDirty/g
s/\bm357z\b/processTimers/g
s/\bm358L\b/updateTimerSlot/g
s/\bm359M\b/computeTimerValue/g
s/\bm360b\b/countLeadingZeros/g
s/\bm361b\b/shiftRightSticky/g
s/\bm362c\b/roundedShiftRight/g
s/\bm363p\b/getThemeColor/g
s/\bm364q\b/getThemeBackground/g
s/\bm365A\b/getScreenMode1/g
s/\bm366B\b/getScreenMode2/g
s/\bm367C\b/getScreenMode3/g
s/\bm368D\b/getScreenMode4/g
s/\bm369N\b/computeLayoutParam/g
s/\bm370r\b/handleViewOption/g
s/\bm371s\b/handleThemeOption/g
s/\bm372g\b/processInputText/g
s/\bm373a\b/handleInputAction/g
s/\bm374t\b/handleSoundOption/g
s/\bm375a\b/createAuthData/g
s/\bm376E\b/getSessionTimestamp/g
s/\bm377a\b/createMrimAuthPacket/g
s/\bm378F\b/clearFormFields/g
s/\bm379f\b/handleFormSubmit/g
s/\bm380a\b/waitForCompletion/g
s/\bm381u\b/handleChatOption/g
s/\bm382g\b/handleConversationAction/g
s/\bm383c\b/interpolateColor/g
s/\bm384v\b/handleChatRoomOption/g
s/\bm385w\b/handleMailboxOption/g
s/\bm386a\b/handleMmpPacket/g
s/\bm387x\b/handleChatListOption/g
s/\bm388y\b/handleChatDetailOption/g
s/\bm389z\b/handleChatSettingsOption/g
s/\bm390G\b/showSettingsScreen/g
s/\bm391H\b/clearSearchResults2/g
s/\bm392I\b/prepareFormData/g
s/\bm393a\b/openUserProfile/g
s/\bm394J\b/clearMapPoints/g
s/\bm395b\b/createPasswordAuthCmd/g
s/\bm396h\b/processPhoneInput/g
s/\bm397h\b/handleSearchAction/g
s/\bm398i\b/handleSearchResultAction/g
s/\bm399K\b/handleInviteAction/g
s/\bm400L\b/handleInviteResult/g
s/\bm401A\b/handleAccountSwitchOption/g
s/\bm402M\b/initChatRoomList/g
s/\bm403a\b/createChatRoomCmd/g
s/\bm404j\b/handleMapSearchAction/g
s/\bm405k\b/handleMapResultAction/g
s/\bm406i\b/processSearchQuery/g
s/\bm407l\b/handleLocationAction/g
s/\bm408B\b/handleMapMenuOption/g
s/\bm409m\b/handleFileAction/g
s/\bm410N\b/hasActiveConnection/g
s/\bm411b\b/markAccountHighlighted/g
s/\bm412O\b/updateTabBar/g
s/\bm413P\b/handleTabAction/g
s/\bm414a\b/markContactRead/g
s/\bm415b\b/markContactUnread/g
s/\bm416b\b/isAccountOnline/g
s/\bm417c\b/getAccountStatus/g
s/\bm418c\b/deleteContact/g
s/\bm419a\b/updateAccountStatus/g
s/\bm420b\b/setAccountOption/g
s/\bm421a\b/processAccountData/g
s/\bm422C\b/addSentBytes/g
s/\bm423D\b/addReceivedBytes/g
s/\bm424E\b/addDownloadBytes/g
s/\bm425F\b/addUploadBytes/g
s/\bm426G\b/addConnectionBytes/g
s/\bm427H\b/addProtocolBytes/g
