# Phase 7c: AppController methods m428-m464 (36)

s/\bm428a\b/getTrafficCount/g
s/\bm429b\b/getTotalTraffic/g
s/\bm430b\b/addTrafficCount/g
s/\bm431af\b/initStartupState/g
s/\bm432ag\b/loadSavedAccounts/g
s/\bm433Q\b/getActiveAccountCount/g
s/\bm434I\b/getAccountByIndex/g
s/\bm435ah\b/saveAccountList/g
s/\bm436a\b/saveState/g
s/\bm437a\b/validateCredentials/g
s/\bm438b\b/createAccount/g
s/\bm439R\b/getMrimAccountList/g
s/\bm440S\b/getOnlineMrimAccounts/g
s/\bm441T\b/getMmpAccountList/g
s/\bm442U\b/getActiveScreenId/g
s/\bm443V\b/getXmppAccountList/g
s/\bm444ai\b/rebuildAccountCaches/g
s/\bm445W\b/getAllAccountsList/g
s/\bm446d\b/getAccountConversations/g
s/\bm447a\b/findMrimAccount/g
s/\bm448X\b/getMapContacts/g
s/\bm449Y\b/getMapProfiles/g
s/\bm450a\b/setFormFields/g
s/\bm451aj\b/computeInitialState/g
s/\bm452Z\b/getLanguageOptions/g
s/\bm453a\b/dispatchCommand/g
s/\bm454aa\b/onSoftKeyPressed/g
s/\bm455ab\b/onItemSelected/g
s/\bm456O\b/getKeyAction/g
s/\bm457ac\b/handleGameAction/g
s/\bm458ak\b/processKeyRepeat/g
s/\bm459a\b/createAddressPair/g
s/\bm460J\b/handleEditAction/g
s/\bm461a\b/handleMrimMailNotify/g
s/\bm462a\b/processMrimMailData/g
s/\bm463n\b/handleIncomingCall/g
s/\bm464a\b/createMmpCommand/g
