# Phase 4: IOUtils (6 fields + 69 methods)

# Fields
s/\bf235a\b/eventType/g
s/\bf236b\b/eventData/g
s/\bf237c\b/openResources/g
s/\bf238d\b/contactIdList/g
s/\bf239e\b/photoUrlList/g
s/\bf240f\b/selectionScreen/g

# Methods
s/\bm752a\b/handleMailMenuAction/g
s/\bm753a\b/createSendMessageCmd/g
s/\bm754a\b/playSound/g
s/\bm755m\b/stopSound/g
s/\bm756a\b/checkSoundTimer/g
s/\bm757a\b/getGroupCount/g
s/\bm758b\b/showAddContactScreen/g
s/\bm759a\b/notifyNewMail/g
s/\bm760c\b/showChatRoomMessages/g
s/\bm768d\b/showPhotoSelector/g
s/\bm769e\b/applyPhotoSelection/g
s/\bm770a\b/handleMapSearch/g
s/\bm771c\b/handleMapPointAction/g
s/\bm772f\b/requestNearbyPeople/g
s/\bm773g\b/postOkEvent/g
s/\bm774h\b/postCancelEvent/g
s/\bm775i\b/postSelectEvent/g
s/\bm776j\b/postBackEvent/g
s/\bm777a\b/postNavigationEvent/g
s/\bm778d\b/postEvent/g
s/\bm779a\b/postRenameError/g
s/\bm780b\b/postAddGroupError/g
s/\bm781c\b/postDeleteError/g
s/\bm782b\b/postOperationError/g
s/\bm783a\b/postAccountError/g
s/\bm784a\b/postAccountMessage/g
s/\bm785b\b/postAccountNotification/g
s/\bm786a\b/postAccountEvent/g
s/\bm787a\b/handleMailForwardAction/g
s/\bm788a\b/createContactCommand/g
s/\bm789a\b/updateContactCommand/g
s/\bm790a\b/deleteContact/g
s/\bm791b\b/blockContact/g
s/\bm792c\b/unblockContact/g
s/\bm793a\b/buildContactListScreen/g
s/\bm794a\b/getCheckedItems/g
s/\bm795b\b/handleContactMenuAction/g
s/\bm796a\b/createHttpResult/g
s/\bm797a\b/createErrorResult/g
s/\bm798a\b/createConnectError/g
s/\bm799b\b/createAuthError/g
s/\bm800c\b/createSendError/g
s/\bm801d\b/createReceiveError/g
s/\bm802e\b/createProtocolError/g
s/\bm803f\b/createGenericError/g
s/\bm804a\b/createHttpRequest/g
s/\bm805a\b/isHttpSuccess/g
s/\bm806e\b/parseJsonResponse/g
s/\bm807b\b/longitudeToPixel/g
s/\bm808c\b/latitudeToPixel/g
s/\bm809a\b/pixelToLongitude/g
s/\bm810b\b/pixelToLatitude/g
s/\bm811e\b/extractLatitude/g
s/\bm812f\b/extractLongitude/g
s/\bm813b\b/sendChatRoomRequest/g
s/\bm814e\b/setSelectedItems/g
s/\bm815g\b/wrapInVector/g
s/\bm816k\b/pollAsyncResult/g
s/\bm817a\b/appendAuthParams/g
s/\bm818c\b/validateJsonResponse/g
s/\bm819l\b/getJsonPayload/g
s/\bm820c\b/loginXmpp/g
s/\bm821a\b/handleFileTransfer/g
s/\bm822a\b/updateContactFlags/g
s/\bm823c\b/handleContactGroupAction/g
s/\bm824d\b/handleStatusChange/g
s/\bm825d\b/transliterate/g
s/\bm826d\b/performXmppAuth/g
s/\bm827a\b/setAuthResult/g
