package com.trykote.mobileagent.core;

/**
 * Generated by tools/cfg_tool.py --gen-keys. Do not edit manually.
 */
public final class ContactKeys {
    private ContactKeys() {}

    public static final int HIDDEN_CONTACTS_LIST = 264;
    public static final int CONTACT_REGISTRY_DATA = 265;
    public static final int FLAG_CONTACT_LIST_ACTIVE = 277;
    public static final int FLAG_REFRESH_CONTACTS = 281;
    public static final int SLOT_CURRENT_CONTACT_ID = 1237;
    public static final int SLOT_NEW_GROUP_NAME = 1295;
    public static final int SLOT_CONTACT_JID = 1296;
    public static final int SLOT_DISPLAY_NAME = 1297;
    public static final int SLOT_SELECTED_GROUP = 1314;
    public static final int SLOT_CONTACT_INFO = 1319;
    public static final int SLOT_GROUP_ADD_NAME = 1320;
    public static final int SLOT_GROUP_ADD_DISPLAY = 1321;
    public static final int SLOT_GROUP_ADD_GROUP = 1322;
    public static final int VEC_GROUP_LIST = 1324;
    public static final int SLOT_GROUP_LIST_INDEX = 1325;
    public static final int SLOT_CURRENT_ENTITY = 1365;
    public static final int VEC_CONTACT_GROUPS = 1400;
    public static final int FLAG_CONTACTS_LOADED = 1478;
    public static final int INT_SELECTED_GROUP_INDEX = 1493;
    public static final int FLAG_IS_MRIM_CONTACT = 1494;
    public static final int SCREEN_FLAGS_START = 1494;
    public static final int FLAG_CONTACT_IS_MRIM = 1495;
    public static final int FLAG_CONTACT_IS_GROUP = 1496;
    public static final int FLAG_CONTACT_IS_USER = 1497;
    public static final int FLAG_CONTACT_IS_ONLINE = 1498;
    public static final int FLAG_CONTACT_HAS_UNREAD = 1499;
    public static final int FLAG_CONTACT_HAS_VCARD = 1501;
    public static final int SCREEN_FLAGS_END = 1501;
    public static final int INT_GROUP_OPERATION_RESULT = 1507;
    public static final int FLAG_GROUP_ADD_RESULT = 1509;
    public static final int INT_CONTACT_ICON_SIZE = 2573;
    public static final int INT_CONTACT_TYPE_CODE = 3510;
    public static final int FLAG_CONTACT_MENU_MODE = 3707;
    public static final int INT_ADD_CONTACT_MODE = 3897;
}
