package com.trykote.mobileagent.core;

/**
 * Generated by editor --gen-palette. Do not edit manually.
 */
public final class PaletteKeys {
    private PaletteKeys() {}

    public static final int COLORS_BASE = 4799;
    public static final int GRADIENT_START = 4927;
    public static final int MAP_FILL = 4935;
    public static final int MAP_BORDER = 4943;
    public static final int MAP_BG = 4951;
    public static final int MAP_PULSE = 4959;
    public static final int GRADIENT_END = 4967;
}
