package com.trykote.mobileagent.core;

/**
 * Generated by editor --gen-palette. Do not edit manually.
 */
public final class PaletteKeys {
    private PaletteKeys() {}

    public static final int COLORS_BASE = 4918;
    public static final int GRADIENT_START = 5046;
    public static final int MAP_FILL = 5054;
    public static final int MAP_BORDER = 5062;
    public static final int MAP_BG = 5070;
    public static final int MAP_PULSE = 5078;
    public static final int GRADIENT_END = 5086;
}
