package com.trykote.mobileagent.core;

/**
 * Generated by tools/cfg_tool.py --gen-keys. Do not edit manually.
 */
public final class SessionKeys {
    private SessionKeys() {}

    public static final int FLAG_INIT_COMPLETE = 217;
    public static final int TIMESTAMP_FIRST_RUN = 219;
    public static final int SESSION_RANDOM_ID = 222;
    public static final int SESSION_KEY = 223;
    public static final int TIMESTAMP_LAST_XMPP_AUTH = 236;
    public static final int SESSION_DEVICE_INFO = 239;
    public static final int LAST_ACCOUNT_NAME = 267;
    public static final int FLAG_HAS_SAVED_ACCOUNTS = 268;
    public static final int FLAG_HAS_XMPP_ACCOUNT = 269;
    public static final int FLAG_HAS_MRIM_ACCOUNT = 270;
    public static final int FLAG_KEEP_SCREEN_ON = 272;
    public static final int TIMESTAMP_LAST_CLEANUP = 274;
    public static final int FLAG_APP_STARTING = 285;
    public static final int FLAG_UPDATE_AVAILABLE = 286;
    public static final int TIMESTAMP_LAST_UPDATE_CHECK = 287;
    public static final int COUNTER_SCREEN_OPENS = 290;
    public static final int COUNTER_APP_STARTS = 291;
    public static final int COUNTER_ERRORS = 292;
    public static final int COUNTER_TOTAL_TRAFFIC = 293;
    public static final int COUNTER_RESERVED = 294;
    /** Папка для хранения карт не найдена. Задать в настройках? */
    public static final int SESSION_PLATFORM_INFO = 403;
    public static final int OBJ_CALLBACK_ARRAY = 1238;
    public static final int VEC_ACCOUNTS = 1241;
    public static final int SLOT_ACTIVE_PROTOCOL_NAME = 1251;
    public static final int SLOT_ACCOUNT_LIST_TEXT = 1252;
    public static final int VEC_EVENT_QUEUE = 1266;
    public static final int SLOT_CURRENT_ACCOUNT = 1281;
    public static final int SLOT_TEMP_ACCOUNT = 1282;
    public static final int VEC_FILTERED_ACCOUNTS = 1283;
    public static final int VEC_ACCOUNT_SELECTION = 1291;
    public static final int OBJ_MIDLET = 1366;
    public static final int OBJ_CALENDAR = 1367;
    public static final int OBJ_DATE = 1368;
    public static final int ARR_EMPTY_INT = 1370;
    public static final int OBJ_CANVAS = 1371;
    public static final int OBJ_RANDOM = 1372;
    public static final int SLOT_ACCOUNT_LOGIN = 1376;
    public static final int SLOT_ACCOUNT_PASSWORD = 1377;
    /** microedition.pim.version */
    public static final int SLOT_ACCOUNT_SERVER = 1378;
    /** microedition.io.file.FileConnection.version */
    public static final int SLOT_ACCOUNT_DISPLAY_NAME = 1379;
    /** microedition.location.version */
    public static final int SLOT_ACCOUNT_TYPE_STR = 1380;
    /** X-MRA-GUID */
    public static final int SLOT_SESSION_HASH = 1381;
    /** X-MRA-Invite */
    public static final int SLOT_SESSION_TOKEN = 1382;
    public static final int INT_ACCOUNT_INDEX = 1438;
    public static final int FLAG_MRIM_DATA_LOADED = 1449;
    public static final int FLAG_HAS_MULTIPLE_MRIM = 1462;
    public static final int FLAG_HAS_MRIM_ACCOUNTS = 1463;
    public static final int FLAG_HAS_MRIM_ACCOUNTS_2 = 1464;
    public static final int FLAG_HAS_XMPP_ACCOUNTS = 1465;
    public static final int INT_TARGET_STATE = 1466;
    public static final int FLAG_CAPTCHA_SHOWN = 1468;
    public static final int FLAG_CLEANUP_DONE = 1471;
    public static final int FLAG_MULTIPLE_MRIM = 1472;
    public static final int FLAG_MULTIPLE_XMPP = 1473;
    public static final int INT_SERVER_INDEX = 1474;
    public static final int INT_PROTOCOL_TYPE = 1475;
    public static final int INT_CONNECTION_STATE = 1476;
    public static final int TIMESTAMP_CURRENT = 1530;
    public static final int TIMESTAMP_OFFSET = 1532;
}
