package com.trykote.mobileagent.core;

/**
 * Generated by tools/cfg_tool.py --gen-keys. Do not edit manually.
 */
public final class StringResKeys {
    private StringResKeys() {}

    public static final int MAILBOX_NAMES_EN_COUNT = 5;
    public static final int MAILBOX_NAMES_RU_COUNT = 5;
    public static final int PHONE_STRINGS_COUNT = 15;
    public static final int MMP_EMOTICONS_COUNT = 43;
    public static final int XMPP_EMOTICONS_COUNT = 47;
    /** block of 15 */
    public static final int PHONE_STRINGS_BASE = 48;
    public static final int EMOTICON_NAMES_COUNT = 60;
    /** Здравствуйте,  */
    public static final int STR_TRAFFIC_INFO_YES = 93;
    /** С уважением */
    public static final int STR_TRAFFIC_INFO_NO = 95;
    /** руб. */
    public static final int STR_CURRENCY_SYMBOL = 117;
    /** Курю */
    public static final int STR_CONFIG_TYPE_BASE = 151;
    /** packed_strings */
    public static final int RES_STRING_DATA = 295;
    /** Эта операция доступна только при соединении с сервером. */
    public static final int STR_XMPP_EVENT = 299;
    /** Местоположение не определено */
    public static final int STR_DEFAULT_LANGUAGE = 308;
    /** , запись в блог,  */
    public static final int STR_NAME_SEPARATOR = 311;
    /** string_list */
    public static final int STR_CONTACT_FIELD_LABELS = 312;
    /** Город:  */
    public static final int STR_LABEL_COMPANY = 313;
    /** Страница:  */
    public static final int STR_LABEL_LOCATION = 314;
    /** Возраст:  */
    public static final int STR_LABEL_AGE = 315;
    /** Примечания:  */
    public static final int STR_LABEL_WEBSITE = 316;
    /** Клиент:  */
    public static final int STR_LABEL_STATUS = 317;
    /** (М) */
    public static final int STR_GENDER_MALE = 318;
    /** (Ж) */
    public static final int STR_GENDER_FEMALE = 319;
    /** не определен */
    public static final int STR_AGE_UNKNOWN = 323;
    /** Слушает:  */
    public static final int STR_SECTION_PHONE = 324;
    /** Микроблог:  */
    public static final int STR_SECTION_EMAIL = 325;
    /** Местоположение:  */
    public static final int STR_SECTION_ABOUT = 326;
    /** Уточнить */
    public static final int STR_SOFTKEY_MAP = 330;
    /** Здравствуйте. Я нашел вас на карте в Mail.Ru Агенте. Пожа... */
    public static final int STR_SOFTKEY_OK = 331;
    /** Показывать закладки */
    public static final int STR_PROTOCOL_MRIM = 376;
    /** Скрывать закладки */
    public static final int STR_PROTOCOL_MMP = 377;
    /** bytes */
    public static final int STR_ACCOUNTS_HEADER = 396;
    /** Очистить карту */
    public static final int STR_PROTOCOL_XMPP = 402;
    /** Следующие 10 */
    public static final int STR_MENU_CALL = 420;
    /** Предыдущие 10 */
    public static final int STR_MENU_SMS = 421;
    /** bytes */
    public static final int STR_INPUT_MODE_DEFAULT = 424;
    /** UCB_BASIC_LATIN */
    public static final int STR_INPUT_MODE_LATIN = 425;
    /** UCB_CYRILLIC */
    public static final int STR_INPUT_MODE_NUMERIC = 426;
    /** bytes */
    public static final int RES_EMOTICON_MAP = 430;
    /**  объект */
    public static final int STR_CONV_SUFFIX_BASE = 442;
    /** Людей в группе:  */
    public static final int STR_CONV_UNREAD_PREFIX = 445;
    /**  и еще  */
    public static final int STR_CONV_SEPARATOR = 446;
    /**  контакт */
    public static final int STR_PHONE_CONTACT_SUFFIX = 447;
    /** Группа ( */
    public static final int STR_PHONE_CONTACTS_PREFIX = 450;
    /** Имя скрыто */
    public static final int STR_ANONYMOUS_NAME = 451;
    /** Ошибка. Возможно, конференция была удалена её создателем */
    public static final int STR_AUTH_GRANTED = 452;
    /** Не удалось доставить сообщение для ' */
    public static final int STR_AUTH_REQUEST = 453;
    /** Не удалось удалить ' */
    public static final int STR_ADDED_TO_LIST = 454;
    /** Не удалось изменить ' */
    public static final int STR_REMOVED_FROM_LIST = 455;
    /** Не удалось добавить ' */
    public static final int STR_TYPING_NOTIFICATION = 456;
    /** '
Код ошибки  */
    public static final int STR_MESSAGE_SEPARATOR = 457;
    /** Ошибка приема контакт-листа  */
    public static final int STR_STATUS_CHANGED = 458;
    /** Соединение ' */
    public static final int STR_ACCOUNT_CONNECTED = 459;
    /** ' потеряно.  */
    public static final int STR_ACCOUNT_SEPARATOR = 460;
    /** Ошибка ростера. */
    public static final int STR_NETWORK_ERROR = 464;
    /** Для стабильной работы ICQ нужна подключенная учетная запи... */
    public static final int STR_MMP_AUTH_ERROR = 479;
    /** Системное сообщение: вас добавили в список контактов */
    public static final int STR_MMP_SYSTEM_MESSAGE = 480;
    /** Сервер вернул ошибку  */
    public static final int STR_MMP_SPAM_REPORT = 481;
    /** . Попробуйте повторить операцию позже. */
    public static final int STR_MMP_SPAM_SUFFIX = 482;
    /** Системное сообщение:  */
    public static final int STR_MMP_FILE_TRANSFER = 483;
    /** Мое местоположение.  */
    public static final int STR_MRIM_OFFLINE_SUFFIX = 488;
    /** Ваше предполагаемое местоположение.  */
    public static final int STR_MRIM_AWAY_SUFFIX = 489;
    /** Запись успешно опубликована */
    public static final int STR_OPERATION_COMPLETE = 494;
    /**  для Java */
    public static final int STR_APP_BUILD_SUFFIX = 511;
    /** Agent-Modules */
    public static final int STR_APP_PROPERTY_NAME = 519;
    /** Показывать мое местоположение:  */
    public static final int STR_LANGUAGE_PREFIX = 522;
    /** Цветовая схема: */
    public static final int STR_MENU_SETTINGS = 560;
    /** bytes */
    public static final int RES_ICON_MAP = 580;
    /** Онлайн */
    public static final int STR_STATUS_ONLINE = 642;
    /** Готов поболтать */
    public static final int STR_STATUS_AWAY = 643;
    /** Отсутствую */
    public static final int STR_STATUS_DND = 644;
    /** Не беспокоить */
    public static final int STR_STATUS_INVISIBLE = 645;
    /** Удалить ' */
    public static final int STR_ALERT_PREFIX = 672;
    /** -любая- */
    public static final int STR_SEARCH_TITLE = 683;
    /** -любой- */
    public static final int STR_CITY_LIST = 684;
    /** string_list */
    public static final int STR_MONTH_NAMES = 685;
    /** string_list */
    public static final int STR_GENDER_LIST = 686;
    /** string_list */
    public static final int STR_AGE_RANGES = 687;
    /** Знак Зодиака: */
    public static final int STR_LABEL_MONTH = 688;
    /** Страна: */
    public static final int STR_LABEL_COUNTRY = 689;
    /** Регион: */
    public static final int STR_LABEL_REGION = 690;
    /** Город: */
    public static final int STR_LABEL_CITY = 691;
    /** День рождения: */
    public static final int STR_LABEL_AGE_RANGE = 692;
    /** Месяц рождения: */
    public static final int STR_LABEL_GENDER = 693;
    /** string_list */
    public static final int STR_DOMAIN_LIST = 694;
    /** string_list */
    public static final int STR_SERVER_SUFFIX_LIST = 695;
    /** string_list */
    public static final int STR_SERVER_LIST = 696;
    /** Здравствуйте! Пожалуйста, добавьте меня в ваш список конт... */
    public static final int STR_DEFAULT_GROUP_NAME = 741;
    /** Нет групп */
    public static final int STR_NOTIFICATION_NEW_MSG = 743;
    /** jid: */
    public static final int STR_LABEL_NOTES = 744;
    /** Очистить архив переписки с ' */
    public static final int STR_DELETE_CONFIRM = 760;
    /** Игнорировать ' */
    public static final int STR_BLOCK_CONFIRM = 768;
    /** Конференция  */
    public static final int STR_CHAT_NAME_PREFIX = 771;
    /** SMS  */
    public static final int STR_FILE_TRANSFER_PREFIX = 776;
    /** Ваше местоположение  */
    public static final int STR_REGISTRATION_TEXT = 780;
    /** Функция "Местоположение" дает возможность указать где вы ... */
    public static final int STR_MRIM_DISCONNECT = 786;
    /** Секретный вопрос: */
    public static final int STR_MENU_OPTIONS = 809;
    /** string_list */
    public static final int STR_MENU_REG_SMS = 810;
    /** Свой вопрос: */
    public static final int STR_MENU_PHONE_PREFIX = 811;
    /** Регистрация */
    public static final int STR_SEARCH_URL = 817;
    /** --- оригинальное сообщение ---
 */
    public static final int STR_SEARCH_QUERY_PREFIX = 838;
    /** Ответить */
    public static final int STR_EXPAND_MESSAGE = 839;
    /** Помеченные ( */
    public static final int STR_UNREAD_COUNT_PREFIX = 849;
    /** От: */
    public static final int STR_MSG_FORWARDED = 867;
    /** Кому: */
    public static final int STR_MSG_REPLIED = 868;
    /** 
-----
Отправлено с помощью Мобильного Агента */
    public static final int STR_TRAFFIC_LABEL = 874;
    /** Письмо успешно отправлено. */
    public static final int STR_PRIVACY_MODE_BASE = 879;
    /** block of 5 */
    public static final int MAILBOX_NAMES_EN_BASE = 891;
    /** Trash */
    public static final int STR_DEFAULT_CHATROOM = 892;
    /** block of 5 */
    public static final int MAILBOX_NAMES_RU_BASE = 896;
    /** Корзина */
    public static final int STR_MAIN_CHATROOM = 897;
    /** Найдено:  */
    public static final int STR_CHATROOM_PREFIX = 901;
    /** (Без темы) */
    public static final int STR_NO_SUBJECT = 902;
    /**  Кб]  */
    public static final int STR_PRIORITY_SUFFIX = 903;
    /** bytes */
    public static final int RES_BLOCKED_GUID = 905;
    /** bytes */
    public static final int RES_UNBLOCKED_GUID = 906;
    /** bytes */
    public static final int RES_SESSION_BYTES = 907;
    /** bytes */
    public static final int RES_AUTH_SLOT_GUIDS = 908;
    /** Собеседник попытался вас разбудить, однако у вас установл... */
    public static final int STR_MRIM_RENAME_CONTACT = 909;
    /** Собеседник попытался вас разбудить */
    public static final int STR_CONFERENCE_INVITE = 910;
    /** [Пригласил в конференцию] */
    public static final int STR_GROUP_MESSAGE = 911;
    /** [Покинул конференцию] */
    public static final int STR_PRIVATE_MESSAGE = 912;
    /** Нет пользователя, удовлетворяющего условиям поиска. */
    public static final int STR_DEFAULT_CONTACT_NAME = 913;
    /** Ошибка при поиске. Код ошибки= */
    public static final int STR_CONTACT_NAME_PREFIX = 914;
    /** string_list */
    public static final int STR_REG_FIELD_NAMES = 915;
    /** Открыть почтовый ящик? */
    public static final int STR_MAIL_PREFIX = 916;
    /** Новое письмо от  */
    public static final int STR_NEW_MAIL_FROM = 917;
    /** У вас  */
    public static final int STR_NEW_MAIL_COUNT = 918;
    /**  новое письмо. */
    public static final int STR_NEW_MAIL_SUFFIX = 919;
    /** Не удалось отправить сообщение для ' */
    public static final int STR_XMPP_SERVICE_MSG = 922;
    /** @chat.agent */
    public static final int STR_BOT_SUFFIX = 923;
    /** Вы попытались разбудить собеседника. */
    public static final int STR_WELCOME_MESSAGE = 924;
    /** . Версия:  */
    public static final int STR_STATUS_TITLE_PREFIX = 944;
    /** bytes */
    public static final int RES_MONTH_DAYS = 945;
    /**  Детали ошибки:  */
    public static final int STR_ERROR_SEPARATOR = 946;
    /** Ошибка обработки данных. */
    public static final int STR_TIMEOUT_ERROR = 951;
    /**  ч.  */
    public static final int STR_HOUR_SEPARATOR = 954;
    /**  мин. */
    public static final int STR_DISTANCE_SUFFIX = 955;
    /** абвгдеёжзийклмнопрстуфхцчшщэюя */
    public static final int STR_SOUND_TYPE_1 = 956;
    /** АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯ */
    public static final int STR_SOUND_TYPE_2 = 957;
    /** string_list */
    public static final int STR_SOUND_LIST = 958;
    /** ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234... */
    public static final int RES_BASE64_TABLE = 961;
    /** bytes */
    public static final int RES_EMOTICON_STATE = 962;
    /** Пробки:  */
    public static final int STR_MAP_INFO_PREFIX = 974;
    /** Начало маршрута; общая длина:  */
    public static final int STR_ROUTE_PREFIX = 979;
    /** Конец маршрута */
    public static final int STR_NO_ROUTE = 980;
    /** 7: назад; 9: вперед */
    public static final int STR_ROUTE_LABEL = 981;
    /** : посмотреть */
    public static final int STR_SHOW_ROUTE = 982;
    /** ; время в пути:  */
    public static final int STR_DISTANCE_UNIT = 983;
    /** INFINITY */
    public static final int STR_INFINITY = 984;
    /** bytes */
    public static final int RES_LOG_BASE_TABLE = 986;
    /** bytes */
    public static final int RES_POW_BASE_TABLE = 987;
    /** bytes */
    public static final int RES_SHORT_INDEX_TABLE_1 = 988;
    /** bytes */
    public static final int RES_SHORT_INDEX_TABLE_2 = 989;
    /** bytes */
    public static final int RES_MULTIPLY_COEFFICIENTS = 990;
    /** bytes */
    public static final int RES_LOOKUP_TABLE = 991;
    /** bytes */
    public static final int RES_PALETTE_MAP_1 = 992;
    /** bytes */
    public static final int RES_PALETTE_MAP_2 = 993;
    /** Посмотреть в картах */
    public static final int STR_CHAT_DEFAULT_TOPIC = 994;
    /** Россия */
    public static final int STR_REGION_NAME_1 = 995;
    /** Москва */
    public static final int STR_REGION_NAME_2 = 996;
    /** Маршрут не найден */
    public static final int STR_DOWNLOAD_COMPLETE = 1001;
    /** com.sonyericsson.net.cellid */
    public static final int RES_UPDATE_DATA = 1004;
    /** Не использовать */
    public static final int STR_DEVICE_FEATURES = 1024;
    /** Не хватает общения? Рекомендуй Мобильный Агент своим друз... */
    public static final int STR_NOTIFY_MESSAGE = 1028;
    /** SMS-приглашения успешно отправлены */
    public static final int STR_EXIT_CONFIRM = 1029;
    /** Системное сообщение: запрос подписки на присутствие */
    public static final int STR_XMPP_AUTH_REQUEST = 1031;
    /**     */
    public static final int STR_PLACEHOLDER_TEXT = 1037;
    public static final int STR_EMPTY = 1038;
    /** Временные */
    public static final int STR_GROUP_DEFAULT = 1039;
    /** Жду авторизации */
    public static final int STR_GROUP_NOT_IN_LIST = 1040;
    /** Телефонные контакты */
    public static final int STR_GROUP_IGNORE = 1041;
    /** Игнорируемые */
    public static final int STR_GROUP_TEMPORARY = 1042;
    /** Конференции */
    public static final int STR_GROUP_PHONE_CONTACTS = 1043;
    /** Почта */
    public static final int STR_TAB_MAIL = 1044;
    /** Карты */
    public static final int STR_TAB_SEARCH = 1045;
    /**   */
    public static final int STR_SPACE = 1046;
    /** Контакты */
    public static final int STR_TAB_CONTACTS = 1047;
    /** Выбрать */
    public static final int STR_SOFTKEY_YES = 1048;
    /** Назад */
    public static final int STR_SOFTKEY_NO = 1050;
    /** Отмена */
    public static final int STR_SOFTKEY_CLOSE = 1055;
    /** Отправить */
    public static final int STR_NOTIFICATION_SOUND = 1060;
    /** Меню */
    public static final int STR_SOFTKEY_MENU = 1062;
    /** block of 60 */
    public static final int EMOTICON_NAMES_BASE = 1063;
    /** block of 43 */
    public static final int MMP_EMOTICONS_BASE = 1141;
    /** block of 47 */
    public static final int XMPP_EMOTICONS_BASE = 1184;
    /** status_chat */
    public static final int STR_CMD_SHOW_MAP = 1224;
    /** status_dnd */
    public static final int STR_CMD_SHOW_LIST = 1225;
    /** status_ */
    public static final int STR_CONFIG_STATUS_PREFIX = 1226;
    /** phone */
    public static final int STR_PHONE_SUFFIX = 1233;
    /** group */
    public static final int STR_PHONE_PREFIX = 1234;
    public static final int STR_SEPARATOR = 1369;
    /** MIDlet-Version */
    public static final int STR_APP_NAME = 1375;
}
