package com.trykote.mobileagent.key;

/**
 * Generated by editor --gen-keys. Do not edit manually.
 */
public final class StringResKeys {
    private StringResKeys() {}

    public static final int MAILBOX_NAMES_EN_COUNT = 5;
    public static final int MAILBOX_NAMES_RU_COUNT = 5;
    public static final int PHONE_STRINGS_COUNT = 15;
    public static final int MMP_EMOTICONS_COUNT = 43;
    public static final int XMPP_EMOTICONS_COUNT = 47;
    public static final int PHONE_STRINGS_BASE = 48;
    public static final int EMOTICON_NAMES_COUNT = 60;
    /** Здравствуйте,  */
    public static final int STR_TRAFFIC_INFO_YES = 93;
    /** С уважением */
    public static final int STR_TRAFFIC_INFO_NO = 95;
    /** руб. */
    public static final int STR_CURRENCY_SYMBOL = 117;
    /** Курю */
    public static final int STR_CONFIG_TYPE_BASE = 151;
    public static final int RES_STRING_DATA = 295;
    /** Эта операция доступна только при соединении с с... */
    public static final int STR_XMPP_EVENT = 299;
    /** Местоположение не определено */
    public static final int STR_DEFAULT_LANGUAGE = 308;
    /** , запись в блог,  */
    public static final int STR_NAME_SEPARATOR = 311;
    public static final int STR_CONTACT_FIELD_LABELS = 312;
    /** Город:  */
    public static final int STR_LABEL_COMPANY = 313;
    /** Страница:  */
    public static final int STR_LABEL_LOCATION = 314;
    /** Возраст:  */
    public static final int STR_LABEL_AGE = 315;
    /** Примечания:  */
    public static final int STR_LABEL_WEBSITE = 316;
    /** Клиент:  */
    public static final int STR_LABEL_STATUS = 317;
    /** (М) */
    public static final int STR_GENDER_MALE = 318;
    /** (Ж) */
    public static final int STR_GENDER_FEMALE = 319;
    /** не определен */
    public static final int STR_AGE_UNKNOWN = 323;
    /** Слушает:  */
    public static final int STR_SECTION_PHONE = 324;
    /** Микроблог:  */
    public static final int STR_SECTION_EMAIL = 325;
    /** Местоположение:  */
    public static final int STR_SECTION_ABOUT = 326;
    /** Уточнить */
    public static final int STR_SOFTKEY_MAP = 330;
    /** Здравствуйте. Я нашел вас на карте в Mail.Ru Аг... */
    public static final int STR_SOFTKEY_OK = 331;
    /** Показывать закладки */
    public static final int STR_PROTOCOL_MRIM = 376;
    /** Скрывать закладки */
    public static final int STR_PROTOCOL_MMP = 377;
    public static final int STR_ACCOUNTS_HEADER = 396;
    /** Очистить карту */
    public static final int STR_PROTOCOL_XMPP = 402;
    /** Следующие 10 */
    public static final int STR_MENU_CALL = 420;
    /** Предыдущие 10 */
    public static final int STR_MENU_SMS = 421;
    public static final int STR_INPUT_MODE_DEFAULT = 424;
    /** UCB_BASIC_LATIN */
    public static final int STR_INPUT_MODE_LATIN = 425;
    /** UCB_CYRILLIC */
    public static final int STR_INPUT_MODE_NUMERIC = 426;
    public static final int RES_EMOTICON_MAP = 430;
    /**  объект */
    public static final int STR_CONV_SUFFIX_BASE = 442;
    /** Людей в группе:  */
    public static final int STR_CONV_UNREAD_PREFIX = 445;
    /**  и еще  */
    public static final int STR_CONV_SEPARATOR = 446;
    /**  контакт */
    public static final int STR_PHONE_CONTACT_SUFFIX = 447;
    /** Группа ( */
    public static final int STR_PHONE_CONTACTS_PREFIX = 450;
    /** Имя скрыто */
    public static final int STR_ANONYMOUS_NAME = 451;
    /** Ошибка. Возможно, конференция была удалена её с... */
    public static final int STR_AUTH_GRANTED = 452;
    /** Не удалось доставить сообщение для ' */
    public static final int STR_AUTH_REQUEST = 453;
    /** Не удалось удалить ' */
    public static final int STR_ADDED_TO_LIST = 454;
    /** Не удалось изменить ' */
    public static final int STR_REMOVED_FROM_LIST = 455;
    /** Не удалось добавить ' */
    public static final int STR_TYPING_NOTIFICATION = 456;
    /** '
Код ошибки  */
    public static final int STR_MESSAGE_SEPARATOR = 457;
    /** Ошибка приема контакт-листа  */
    public static final int STR_STATUS_CHANGED = 458;
    /** Соединение ' */
    public static final int STR_ACCOUNT_CONNECTED = 459;
    /** ' потеряно.  */
    public static final int STR_ACCOUNT_SEPARATOR = 460;
    /** Ошибка ростера. */
    public static final int STR_NETWORK_ERROR = 464;
    /** Для стабильной работы ICQ нужна подключенная уч... */
    public static final int STR_MMP_AUTH_ERROR = 479;
    /** Системное сообщение: вас добавили в список конт... */
    public static final int STR_MMP_SYSTEM_MESSAGE = 480;
    /** Сервер вернул ошибку  */
    public static final int STR_MMP_SPAM_REPORT = 481;
    /** . Попробуйте повторить операцию позже. */
    public static final int STR_MMP_SPAM_SUFFIX = 482;
    /** Системное сообщение:  */
    public static final int STR_MMP_FILE_TRANSFER = 483;
    /** Мое местоположение.  */
    public static final int STR_MRIM_OFFLINE_SUFFIX = 488;
    /** Ваше предполагаемое местоположение.  */
    public static final int STR_MRIM_AWAY_SUFFIX = 489;
    /** Запись успешно опубликована */
    public static final int STR_OPERATION_COMPLETE = 494;
    /**  для Java */
    public static final int STR_APP_BUILD_SUFFIX = 511;
    /** Agent-Modules */
    public static final int STR_APP_PROPERTY_NAME = 519;
    /** Показывать мое местоположение:  */
    public static final int STR_LANGUAGE_PREFIX = 522;
    /** Цветовая схема: */
    public static final int STR_MENU_SETTINGS = 560;
    public static final int RES_ICON_MAP = 580;
    /** Онлайн */
    public static final int STR_STATUS_ONLINE = 642;
    /** Готов поболтать */
    public static final int STR_STATUS_AWAY = 643;
    /** Отсутствую */
    public static final int STR_STATUS_DND = 644;
    /** Не беспокоить */
    public static final int STR_STATUS_INVISIBLE = 645;
    /** Удалить ' */
    public static final int STR_ALERT_PREFIX = 672;
    /** -любая- */
    public static final int STR_SEARCH_TITLE = 683;
    /** -любой- */
    public static final int STR_CITY_LIST = 684;
    public static final int STR_MONTH_NAMES = 685;
    public static final int STR_GENDER_LIST = 686;
    public static final int STR_AGE_RANGES = 687;
    /** Знак Зодиака: */
    public static final int STR_LABEL_MONTH = 688;
    /** Страна: */
    public static final int STR_LABEL_COUNTRY = 689;
    /** Регион: */
    public static final int STR_LABEL_REGION = 690;
    /** Город: */
    public static final int STR_LABEL_CITY = 691;
    /** День рождения: */
    public static final int STR_LABEL_AGE_RANGE = 692;
    /** Месяц рождения: */
    public static final int STR_LABEL_GENDER = 693;
    public static final int STR_DOMAIN_LIST = 694;
    public static final int STR_SERVER_SUFFIX_LIST = 695;
    public static final int STR_SERVER_LIST = 696;
    /** Здравствуйте! Пожалуйста, добавьте меня в ваш с... */
    public static final int STR_DEFAULT_GROUP_NAME = 741;
    /** Нет групп */
    public static final int STR_NOTIFICATION_NEW_MSG = 743;
    /** jid: */
    public static final int STR_LABEL_NOTES = 744;
    /** Очистить архив переписки с ' */
    public static final int STR_DELETE_CONFIRM = 760;
    /** Игнорировать ' */
    public static final int STR_BLOCK_CONFIRM = 768;
    /** Конференция  */
    public static final int STR_CHAT_NAME_PREFIX = 771;
    /** SMS  */
    public static final int STR_FILE_TRANSFER_PREFIX = 776;
    /** Ваше местоположение  */
    public static final int STR_REGISTRATION_TEXT = 780;
    /** Функция "Местоположение" дает возможность указа... */
    public static final int STR_MRIM_DISCONNECT = 786;
    /** Секретный вопрос: */
    public static final int STR_MENU_OPTIONS = 809;
    public static final int STR_MENU_REG_SMS = 810;
    /** Свой вопрос: */
    public static final int STR_MENU_PHONE_PREFIX = 811;
    /** Регистрация */
    public static final int STR_SEARCH_URL = 817;
    /** --- оригинальное сообщение ---
 */
    public static final int STR_SEARCH_QUERY_PREFIX = 838;
    /** Ответить */
    public static final int STR_EXPAND_MESSAGE = 839;
    /** Помеченные ( */
    public static final int STR_UNREAD_COUNT_PREFIX = 849;
    /** От: */
    public static final int STR_MSG_FORWARDED = 867;
    /** Кому: */
    public static final int STR_MSG_REPLIED = 868;
    /** 
-----
Отправлено с помощью Мобильного Агента */
    public static final int STR_TRAFFIC_LABEL = 874;
    /** Письмо успешно отправлено. */
    public static final int STR_PRIVACY_MODE_BASE = 879;
    public static final int MAILBOX_NAMES_EN_BASE = 891;
    /** Trash */
    public static final int STR_DEFAULT_CHATROOM = 892;
    public static final int MAILBOX_NAMES_RU_BASE = 896;
    /** Корзина */
    public static final int STR_MAIN_CHATROOM = 897;
    /** Найдено:  */
    public static final int STR_CHATROOM_PREFIX = 901;
    /** (Без темы) */
    public static final int STR_NO_SUBJECT = 902;
    /**  Кб]  */
    public static final int STR_PRIORITY_SUFFIX = 903;
    public static final int RES_BLOCKED_GUID = 905;
    public static final int RES_UNBLOCKED_GUID = 906;
    public static final int RES_SESSION_BYTES = 907;
    public static final int RES_AUTH_SLOT_GUIDS = 908;
    /** Собеседник попытался вас разбудить, однако у ва... */
    public static final int STR_MRIM_RENAME_CONTACT = 909;
    /** Собеседник попытался вас разбудить */
    public static final int STR_CONFERENCE_INVITE = 910;
    /** [Пригласил в конференцию] */
    public static final int STR_GROUP_MESSAGE = 911;
    /** [Покинул конференцию] */
    public static final int STR_PRIVATE_MESSAGE = 912;
    /** Нет пользователя, удовлетворяющего условиям пои... */
    public static final int STR_DEFAULT_CONTACT_NAME = 913;
    /** Ошибка при поиске. Код ошибки= */
    public static final int STR_CONTACT_NAME_PREFIX = 914;
    public static final int STR_REG_FIELD_NAMES = 915;
    /** Открыть почтовый ящик? */
    public static final int STR_MAIL_PREFIX = 916;
    /** Новое письмо от  */
    public static final int STR_NEW_MAIL_FROM = 917;
    /** У вас  */
    public static final int STR_NEW_MAIL_COUNT = 918;
    /**  новое письмо. */
    public static final int STR_NEW_MAIL_SUFFIX = 919;
    /** Не удалось отправить сообщение для ' */
    public static final int STR_XMPP_SERVICE_MSG = 922;
    /** @chat.agent */
    public static final int STR_BOT_SUFFIX = 923;
    /** Вы попытались разбудить собеседника. */
    public static final int STR_WELCOME_MESSAGE = 924;
    /** . Версия:  */
    public static final int STR_STATUS_TITLE_PREFIX = 944;
    public static final int RES_MONTH_DAYS = 945;
    /**  Детали ошибки:  */
    public static final int STR_ERROR_SEPARATOR = 946;
    /** Ошибка обработки данных. */
    public static final int STR_TIMEOUT_ERROR = 951;
    /**  ч.  */
    public static final int STR_HOUR_SEPARATOR = 954;
    /**  мин. */
    public static final int STR_DISTANCE_SUFFIX = 955;
    /** абвгдеёжзийклмнопрстуфхцчшщэюя */
    public static final int STR_SOUND_TYPE_1 = 956;
    /** АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯ */
    public static final int STR_SOUND_TYPE_2 = 957;
    public static final int STR_SOUND_LIST = 958;
    /** ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu... */
    public static final int RES_BASE64_TABLE = 961;
    public static final int RES_EMOTICON_STATE = 962;
    /** Пробки:  */
    public static final int STR_MAP_INFO_PREFIX = 974;
    /** Начало маршрута; общая длина:  */
    public static final int STR_ROUTE_PREFIX = 979;
    /** Конец маршрута */
    public static final int STR_NO_ROUTE = 980;
    /** 7: назад; 9: вперед */
    public static final int STR_ROUTE_LABEL = 981;
    /** : посмотреть */
    public static final int STR_SHOW_ROUTE = 982;
    /** ; время в пути:  */
    public static final int STR_DISTANCE_UNIT = 983;
    /** INFINITY */
    public static final int STR_INFINITY = 984;
    public static final int RES_LOG_BASE_TABLE = 986;
    public static final int RES_POW_BASE_TABLE = 987;
    public static final int RES_SHORT_INDEX_TABLE_1 = 988;
    public static final int RES_SHORT_INDEX_TABLE_2 = 989;
    public static final int RES_MULTIPLY_COEFFICIENTS = 990;
    public static final int RES_LOOKUP_TABLE = 991;
    public static final int RES_PALETTE_MAP_1 = 992;
    public static final int RES_PALETTE_MAP_2 = 993;
    /** Посмотреть в картах */
    public static final int STR_CHAT_DEFAULT_TOPIC = 994;
    /** Россия */
    public static final int STR_REGION_NAME_1 = 995;
    /** Москва */
    public static final int STR_REGION_NAME_2 = 996;
    /** Маршрут не найден */
    public static final int STR_DOWNLOAD_COMPLETE = 1001;
    /** com.sonyericsson.net.cellid */
    public static final int RES_UPDATE_DATA = 1004;
    /** Не использовать */
    public static final int STR_DEVICE_FEATURES = 1024;
    /** Не хватает общения? Рекомендуй Мобильный Агент ... */
    public static final int STR_NOTIFY_MESSAGE = 1028;
    /** SMS-приглашения успешно отправлены */
    public static final int STR_EXIT_CONFIRM = 1029;
    /** Системное сообщение: запрос подписки на присутс... */
    public static final int STR_XMPP_AUTH_REQUEST = 1031;
    /**     */
    public static final int STR_PLACEHOLDER_TEXT = 1037;
    public static final int STR_EMPTY = 1038;
    /** Временные */
    public static final int STR_GROUP_DEFAULT = 1039;
    /** Жду авторизации */
    public static final int STR_GROUP_NOT_IN_LIST = 1040;
    /** Телефонные контакты */
    public static final int STR_GROUP_IGNORE = 1041;
    /** Игнорируемые */
    public static final int STR_GROUP_TEMPORARY = 1042;
    /** Конференции */
    public static final int STR_GROUP_PHONE_CONTACTS = 1043;
    /** Почта */
    public static final int STR_TAB_MAIL = 1044;
    /** Карты */
    public static final int STR_TAB_SEARCH = 1045;
    /**   */
    public static final int STR_SPACE = 1046;
    /** Контакты */
    public static final int STR_TAB_CONTACTS = 1047;
    /** Выбрать */
    public static final int STR_SOFTKEY_YES = 1048;
    /** Назад */
    public static final int STR_SOFTKEY_NO = 1050;
    /** Отмена */
    public static final int STR_SOFTKEY_CLOSE = 1055;
    /** Отправить */
    public static final int STR_NOTIFICATION_SOUND = 1060;
    /** Меню */
    public static final int STR_SOFTKEY_MENU = 1062;
    public static final int EMOTICON_NAMES_BASE = 1063;
    public static final int MMP_EMOTICONS_BASE = 1141;
    public static final int XMPP_EMOTICONS_BASE = 1184;
    /** status_chat */
    public static final int STR_CMD_SHOW_MAP = 1224;
    /** status_dnd */
    public static final int STR_CMD_SHOW_LIST = 1225;
    /** status_ */
    public static final int STR_CONFIG_STATUS_PREFIX = 1226;
    /** phone */
    public static final int STR_PHONE_SUFFIX = 1233;
    /** group */
    public static final int STR_PHONE_PREFIX = 1234;
    public static final int STR_SEPARATOR = 1369;
    /** MIDlet-Version */
    public static final int STR_APP_NAME = 1375;
    /** a */
    public static final int TAG_A = 65538;
    /** 5 */
    public static final int XMPP_PRIORITY_DEFAULT = 65747;
    /** q= */
    public static final int PARAM_Q_EQ = 131082;
    /** id */
    public static final int ATTR_ID = 131550;
    /** to */
    public static final int ATTR_TO = 131590;
    /** a= */
    public static final int PARAM_A_EQ = 132058;
    /** ID */
    public static final int ATTR_ID_UPPER = 132297;
    /** OK */
    public static final int STATUS_OK = 133005;
    /** To */
    public static final int MAIL_FIELD_TO = 133118;
    /** os */
    public static final int TAG_OS = 133230;
    /** -- */
    public static final int MRIM_MESSAGE_DELIMITER = 134123;
    /** iq */
    public static final int XMPP_IQ = 136604;
    /** xa */
    public static final int XMPP_STATUS_XA = 136761;
    /** "> */
    public static final int XML_CLOSE_TAG_END = 136911;
    /** get */
    public static final int XMPP_TYPE_GET = 196633;
    /** (?) */
    public static final int PLACEHOLDER_UNKNOWN = 197069;
    /** 200 */
    public static final int HTTP_STATUS_200 = 197596;
    /** fw: */
    public static final int PREFIX_FORWARD = 198546;
    /** re: */
    public static final int PREFIX_REPLY = 198549;
    /** set */
    public static final int XMPP_TYPE_SET = 198841;
    /** &y= */
    public static final int PARAM_Y_EQ = 201188;
    /** dir */
    public static final int ATTR_DIR = 201594;
    /** dnd */
    public static final int XMPP_STATUS_DND = 202299;
    /** inv */
    public static final int XMPP_STATUS_INV = 202302;
    /** ask */
    public static final int ATTR_ASK = 202403;
    /** jid */
    public static final int ATTR_JID = 202421;
    /** data */
    public static final int TAG_DATA = 262156;
    /** type */
    public static final int ATTR_TYPE = 262589;
    /** name */
    public static final int ATTR_NAME = 262601;
    /** from */
    public static final int ATTR_FROM = 262852;
    /** link */
    public static final int TAG_LINK = 263156;
    /** UIN: */
    public static final int PREFIX_UIN = 263250;
    /** auth */
    public static final int TAG_AUTH = 263757;
    /** send */
    public static final int ACTION_SEND = 263849;
    /** true */
    public static final int VALUE_TRUE = 264068;
    /** Body */
    public static final int MAIL_FIELD_BODY = 264133;
    /** From */
    public static final int MAIL_FIELD_FROM = 264203;
    /** Date */
    public static final int MAIL_FIELD_DATE = 264254;
    /** copy */
    public static final int MAIL_ACTION_COPY = 264258;
    /** j2me */
    public static final int PLATFORM_J2ME = 264455;
    /** port */
    public static final int TAG_PORT = 265005;
    /** host */
    public static final int TAG_HOST = 265052;
    /** GET& */
    public static final int HTTP_GET_AMP = 265078;
    /** chat */
    public static final int XMPP_TYPE_CHAT = 265215;
    /** %D0% */
    public static final int URL_ENCODE_D0 = 266215;
    /** %D1% */
    public static final int URL_ENCODE_D1 = 266221;
    /** text */
    public static final int CONTENT_TYPE_TEXT = 267133;
    /** nick */
    public static final int TAG_NICK = 267628;
    /** bind */
    public static final int XMPP_BIND = 267762;
    /** ping */
    public static final int TAG_PING = 267810;
    /** away */
    public static final int XMPP_STATUS_AWAY = 267829;
    /** show */
    public static final int TAG_SHOW = 267927;
    /** none */
    public static final int VALUE_NONE = 267931;
    /** item */
    public static final int TAG_ITEM = 267942;
    /** body */
    public static final int TAG_BODY = 267946;
    /** email */
    public static final int ATTR_EMAIL = 328413;
    /** value */
    public static final int ATTR_VALUE = 329117;
    /** false */
    public static final int VALUE_FALSE = 329608;
    /** mList */
    public static final int MAIL_PARAM_MLIST = 329636;
    /** draft */
    public static final int MAIL_FOLDER_DRAFT = 329772;
    /** fList */
    public static final int MAIL_PARAM_FLIST = 329785;
    /** Mpop= */
    public static final int COOKIE_MPOP = 329959;
    /** token */
    public static final int TAG_TOKEN = 330583;
    /** &pwd= */
    public static final int PARAM_PWD = 330609;
    /** tiles */
    public static final int MAP_TILES = 332005;
    /** PLAIN */
    public static final int AUTH_MECHANISM_PLAIN = 332816;
    /** xmlns */
    public static final int XML_ATTR_XMLNS = 333027;
    /** vcard */
    public static final int TAG_VCARD = 333350;
    /** query */
    public static final int TAG_QUERY = 333360;
    /** photo */
    public static final int TAG_PHOTO = 333436;
    /** error */
    public static final int TAG_ERROR = 333441;
    /** vCard */
    public static final int TAG_VCARD_UPPER = 333452;
    /** group */
    public static final int XMPP_GROUP_TAG = 333508;
    /**   !  */
    public static final int MMP_SPACER = 333750;
    /** &rand= */
    public static final int PARAM_RAND = 393943;
    /** &lon1= */
    public static final int PARAM_LON1 = 393954;
    /** &lat2= */
    public static final int PARAM_LAT2 = 393960;
    /** &lon2= */
    public static final int PARAM_LON2 = 393966;
    /** status */
    public static final int TAG_STATUS = 394658;
    /** &data= */
    public static final int PARAM_DATA_EQ = 395134;
    /** ToName */
    public static final int MAIL_FIELD_TO_NAME = 395262;
    /** cookie */
    public static final int TAG_COOKIE = 395483;
    /** secret */
    public static final int TAG_SECRET = 396139;
    /**  alt=' */
    public static final int EMOTICON_ALT_ATTR = 396261;
    /** Sender */
    public static final int MAIL_FIELD_SENDER = 396269;
    /** %D0%81 */
    public static final int URL_ENCODE_YO_UPPER = 397287;
    /** %D1%91 */
    public static final int URL_ENCODE_YO_LOWER = 397293;
    /** points */
    public static final int TAG_POINTS = 397424;
    /** sms:// */
    public static final int SCHEME_SMS = 398209;
    /** nonce= */
    public static final int DIGEST_NONCE_EQ = 398406;
    /** Jabber */
    public static final int XMPP_RESOURCE_JABBER = 398518;
    /** binval */
    public static final int TAG_BINVAL = 398966;
    /** result */
    public static final int TAG_RESULT = 398982;
    /** active */
    public static final int XMPP_CHATSTATES_ACTIVE = 398993;
    /** remove */
    public static final int TAG_REMOVE = 399049;
    /** http:// */
    public static final int SCHEME_HTTP = 459255;
    /** General */
    public static final int XMPP_GROUP_GENERAL = 459528;
    /** version */
    public static final int TAG_VERSION = 459728;
    /** &c=2&e= */
    public static final int PARAM_CE = 459750;
    /** &z=java */
    public static final int PARAM_Z_JAVA = 459757;
    /** Receipt */
    public static final int MAIL_FIELD_RECEIPT = 460784;
    /** ToEmail */
    public static final int MAIL_FIELD_TO_EMAIL = 460804;
    /** Subject */
    public static final int MAIL_FIELD_SUBJECT = 460837;
    /** loginid */
    public static final int TAG_LOGINID = 461648;
    /** session */
    public static final int TAG_SESSION = 461668;
    /** "   > < */
    public static final int HTML_ENTITY_VALUES = 462816;
    /** &login= */
    public static final int PARAM_LOGIN = 463517;
    /** success */
    public static final int TAG_SUCCESS = 464473;
    /** message */
    public static final int TAG_MESSAGE = 464488;
    /** failure */
    public static final int TAG_FAILURE = 464495;
    /** subject */
    public static final int TAG_SUBJECT = 464558;
    /** data/add */
    public static final int API_DATA_ADD = 524300;
    /** data/get */
    public static final int API_DATA_GET = 524308;
    /** MAPPOINT */
    public static final int MRIM_MAPPOINT = 525044;
    /** geo-list */
    public static final int MRIM_GEO_LIST = 525167;
    /** mListAll */
    public static final int MAIL_PARAM_MLIST_ALL = 526244;
    /** FromName */
    public static final int MAIL_FIELD_FROM_DISPLAY = 526365;
    /** realName */
    public static final int MAIL_FIELD_REAL_NAME = 526385;
    /** hosttime */
    public static final int TAG_HOSTTIME = 527196;
    /** listlink */
    public static final int TAG_LISTLINK = 529266;
    /** response */
    public static final int TAG_RESPONSE = 529537;
    /** presence */
    public static final int TAG_PRESENCE = 530016;
    /** resource */
    public static final int XMPP_RESOURCE = 530129;
    /** priority */
    public static final int XMPP_PRIORITY = 530137;
    /** &digest= */
    public static final int PARAM_DIGEST = 530513;
    /** :vk.com: */
    public static final int DOMAIN_VK_COM = 530521;
    /** MThd     */
    public static final int MIDI_HEADER = 590318;
    /** MAPOBJECT */
    public static final int MRIM_MAPOBJECT = 590588;
    /** geo-point */
    public static final int MRIM_GEO_POINT = 590694;
    /** lastMsgId */
    public static final int MAIL_FIELD_LAST_MSG_ID = 591768;
    /** ClearSize */
    public static final int MAIL_FIELD_CLEAR_SIZE = 591847;
    /** FromEmail */
    public static final int MAIL_FIELD_FROM_EMAIL = 591883;
    /** MessageId */
    public static final int MAIL_FIELD_MESSAGE_ID = 591892;
    /** '</SMILE> */
    public static final int EMOTICON_CLOSE_TAG = 592851;
    /** :;8}$SB() */
    public static final int EMOTICON_TRIGGER_CHARS = 592860;
    /** socket:// */
    public static final int SCHEME_SOCKET = 593549;
    /** timestamp */
    public static final int ATTR_TIMESTAMP = 594023;
    /** subscribe */
    public static final int XMPP_SUBSCRIBE = 594926;
    /** mechanism */
    public static final int ATTR_MECHANISM = 594936;
    /** insisible */
    public static final int XMPP_STATUS_INVISIBLE = 594975;
    /** available */
    public static final int XMPP_STATUS_AVAILABLE = 594984;
    /** ",realm=" */
    public static final int DIGEST_REALM = 595003;
    /** ",nonce=" */
    public static final int DIGEST_NONCE = 595012;
    /** challenge */
    public static final int TAG_CHALLENGE = 595536;
    /** statistics */
    public static final int TAG_STATISTICS = 655360;
    /** audio/midi */
    public static final int MIME_TYPE_MIDI = 655831;
    /** HAS_MYMAIL */
    public static final int MRIM_HAS_MYMAIL = 656203;
    /** &Password= */
    public static final int PARAM_PASSWORD_EQ = 656925;
    /** FlagAttach */
    public static final int MAIL_FLAG_ATTACH = 657363;
    /** FlagUnread */
    public static final int MAIL_FLAG_UNREAD = 657373;
    /** set-cookie */
    public static final int HEADER_SET_COOKIE = 657623;
    /** statuscode */
    public static final int TAG_STATUSCODE = 658246;
    /** <SMILE>id= */
    public static final int EMOTICON_OPEN_TAG = 658377;
    /** &user_lat= */
    public static final int PARAM_USER_LAT = 659815;
    /** &user_lon= */
    public static final int PARAM_USER_LON = 659825;
    /** &x_screen= */
    public static final int PARAM_X_SCREEN = 659835;
    /** &y_screen= */
    public static final int PARAM_Y_SCREEN = 659845;
    /** Secret_389 */
    public static final int SECRET_KEY_389 = 660328;
    /** subscribed */
    public static final int XMPP_SUBSCRIBED = 660462;
    /** mechanisms */
    public static final int XMPP_MECHANISMS = 660472;
    /** DIGEST-MD5 */
    public static final int AUTH_DIGEST_MD5 = 660501;
    /** username=" */
    public static final int DIGEST_USERNAME = 660529;
    /** :00000001: */
    public static final int DIGEST_NC = 660619;
    /** @gmail.com */
    public static final int DOMAIN_GMAIL_COM = 660807;
    /** vcard-temp */
    public static final int XMPP_NS_VCARD_TEMP = 661030;
    /** _phone_info */
    public static final int API_PHONE_INFO = 720924;
    /** ajax_call=1 */
    public static final int PARAM_AJAX_CALL = 722608;
    /** Attachments */
    public static final int MAIL_FIELD_ATTACHMENTS = 722874;
    /** snap_logins */
    public static final int TAG_SNAP_LOGINS = 723889;
    /** AjaxResponse */
    public static final int TAG_AJAX_RESPONSE = 788024;
    /** &sig_sha256= */
    public static final int PARAM_SIG_SHA256 = 789306;
    /** X-MRIM-Flags */
    public static final int HEADER_X_MRIM_FLAGS = 789512;
    /** unsubscribed */
    public static final int XMPP_UNSUBSCRIBED = 791532;
    /** ",response=" */
    public static final int DIGEST_RESPONSE = 791679;
    /** subscription */
    public static final int ATTR_SUBSCRIPTION = 792248;
    /**          */
    public static final int MMP_PADDING_12 = 792490;
    /** VolumeControl */
    public static final int MIDP_VOLUME_CONTROL = 852449;
    /** MRIM.NICKNAME */
    public static final int MRIM_NICKNAME = 852768;
    /** sessionsecret */
    public static final int TAG_SESSIONSECRET = 854884;
    /** <###20###img0 */
    public static final int EMOTICON_TAG_PREFIX = 854972;
    /** stream:stream */
    public static final int XMPP_STREAM_STREAM = 857301;
    /** urn:xmpp:ping */
    public static final int XMPP_NS_PING = 857625;
    /** ReceiptArrived */
    public static final int MAIL_FIELD_RECEIPT_ARRIVED = 919536;
    /** Content-Length */
    public static final int HEADER_CONTENT_LENGTH = 919712;
    /** X-GOOGLE-TOKEN */
    public static final int HEADER_X_GOOGLE_TOKEN = 922626;
    /** MESSAGES.UNREAD */
    public static final int MRIM_MESSAGES_UNREAD = 983853;
    /** client.endpoint */
    public static final int MRIM_CLIENT_ENDPOINT = 983868;
    /** MobileJMEAgent  */
    public static final int USERAGENT_MOBILEJME = 986750;
    /** data/jams_state */
    public static final int API_JAMS_STATE = 987652;
    /** ",charset=utf-8 */
    public static final int DIGEST_CHARSET = 988327;
    /** stream:features */
    public static final int XMPP_STREAM_FEATURES = 988737;
    /** vkmessenger.com */
    public static final int HOST_VKMESSENGER = 989287;
    /** data/agentupload */
    public static final int API_AGENTUPLOAD = 1049531;
    /** /cgi-bin/mailbox */
    public static final int URL_PATH_MAILBOX = 1050207;
    /**      @зз     */
    public static final int MMP_LOGIN_HEADER = 1051079;
    /** mrim_sms@mail.ru */
    public static final int MRIM_SMS_ADDRESS = 1052223;
    /** content-length:  */
    public static final int HEADER_CONTENT_LENGTH_LC = 1052310;
    /** jabber:iq:roster */
    public static final int XMPP_NS_ROSTER = 1054101;
    /** 194.32.248.3:2042 */
    public static final int HOST_MRIM_REDIRECT = 1114895;
    /** geo.point.suggest */
    public static final int MRIM_GEO_SUGGEST = 1114965;
    /** security_image_id */
    public static final int TAG_SECURITY_IMAGE_ID = 1115488;
    /** http://aj.mail.ru */
    public static final int URL_AJ_MAIL_RU = 1115687;
    /** Mobile Mail Agent */
    public static final int XMPP_CLIENT_NAME = 1119195;
    /** jabber:iq:version */
    public static final int XMPP_NS_VERSION = 1119653;
    /** AUTHENTICATE:xmpp/ */
    public static final int DIGEST_AUTH_XMPP = 1184917;
    /** _xmpp-client._tcp. */
    public static final int SRV_XMPP_CLIENT_TCP = 1185660;
    /** http://maps.mail.ru */
    public static final int URL_MAPS_MAIL_RU = 1245774;
    /** security_image_link */
    public static final int TAG_SECURITY_IMAGE_LINK = 1246602;
    /** &quantity=10&idfrom= */
    public static final int PARAM_QUANTITY_IDFROM = 1311413;
    /** &dist=100&sn=1&rand= */
    public static final int PARAM_DIST_RAND = 1311433;
    /** mobile.mail.ru:2041/ */
    public static final int HOST_MOBILE_MAIL_RU_2041 = 1311655;
    /** %40gmail.com&Passwd= */
    public static final int GMAIL_PASSWD = 1316577;
    /** SessionSecure&nonce= */
    public static final int AUTH_SESSION_NONCE = 1316925;
    /** &quantity=50&density= */
    public static final int PARAM_QUANTITY_DENSITY = 1376928;
    /** /cgi-bin/ajax_markmsg */
    public static final int URL_PATH_AJAX_MARKMSG = 1377771;
    /** /cgi-bin/ajax_readmsg */
    public static final int URL_PATH_AJAX_READMSG = 1377926;
    /** /cgi-bin/ajax_sendmsg */
    public static final int URL_PATH_AJAX_SENDMSG = 1377947;
    /** X-MRIM-Multichat-Type */
    public static final int HEADER_X_MRIM_MULTICHAT = 1379315;
    /** http://mobile.mail.ru/ */
    public static final int URL_MOBILE_MAIL_RU = 1442705;
    /**            ru        */
    public static final int MMP_AGENT_ID = 1442808;
    /** ",nc=00000001,cnonce=" */
    public static final int DIGEST_NC_CNONCE = 1446989;
    /** /cgi-bin/ajax_spamabuse */
    public static final int URL_PATH_AJAX_SPAMABUSE = 1508975;
    /** &func_name=majax_search */
    public static final int FUNC_MAJAX_SEARCH = 1509223;
    /** &quot; &nbsp; &gt; &lt; */
    public static final int HTML_ENTITY_NAMES = 1511369;
    /** mobilemaps.mail.ru:2043 */
    public static final int HOST_MOBILEMAPS_2043 = 1511542;
    /** data/mapssearch_ver1?q= */
    public static final int API_MAPSSEARCH = 1511760;
    /** &func_name=ajax_mark_msg */
    public static final int FUNC_AJAX_MARK_MSG = 1574400;
    /** &func_name=ajax_send_msg */
    public static final int FUNC_AJAX_SEND_MSG = 1574735;
    /** &func_name=ajax_spamabuse */
    public static final int FUNC_AJAX_SPAMABUSE = 1640123;
    /** &func_name=ajax_move_msgs */
    public static final int FUNC_AJAX_MOVE_MSGS = 1640193;
    /** &func_name=majax_get_msgs */
    public static final int FUNC_MAJAX_GET_MSGS = 1640218;
    /** client="jagent" version=" */
    public static final int MRIM_CLIENT_VERSION = 1642077;
    /** http://obraz.foto.mail.ru/ */
    public static final int URL_OBRAZ_FOTO = 1704439;
    /**    ru         geo-list */
    public static final int MRIM_GEO_LIST_PACKET = 1704823;
    /** /cgi-bin/auth?lite=1&Login= */
    public static final int URL_PATH_AUTH_LOGIN = 1771076;
    /** &dist=100&sn=1&bestobject=1 */
    public static final int PARAM_MAP_BESTOBJECT = 1774025;
    /** &func_name=ajax_get_msg_data */
    public static final int FUNC_AJAX_GET_MSG_DATA = 1836851;
    /** ",qop=auth,digest-uri="xmpp/ */
    public static final int DIGEST_QOP_AUTH = 1840227;
    /** datagram://nsrpub.mail.ru:53 */
    public static final int HOST_NSRPUB_DNS = 1841038;
    /** http://geo194.32.248.3/?lat1= */
    public static final int URL_GEO_LAT1 = 1901187;
    /** data/road_info_xml?timestamp= */
    public static final int API_ROAD_INFO = 1905127;
    /** http://jabber.org/protocol/nick */
    public static final int XMPP_NS_NICK = 2037073;
    /** &func_name=ajax_get_mailbox_data */
    public static final int FUNC_AJAX_GET_MAILBOX = 2098635;
    /** urn:ietf:params:xml:ns:xmpp-sasl */
    public static final int XMPP_NS_SASL = 2102710;
    /** urn:ietf:params:xml:ns:xmpp-bind */
    public static final int XMPP_NS_BIND = 2102742;
    /** http://xhtml.wap.mail.ru/cgi-bin/ */
    public static final int URL_XHTML_WAP_MAIL_RU = 2163862;
    /** GET /TileSender.aspx?ModeKey=tiles */
    public static final int HTTP_GET_TILESENDER = 2232520;
    /** http://mrb.mail.ru/java/version.txt */
    public static final int URL_VERSION_CHECK = 2295208;
    /** urn:ietf:params:xml:ns:xmpp-session */
    public static final int XMPP_NS_SESSION = 2299382;
    /** &mode=map&fullscreen=true&jams=false */
    public static final int PARAM_MAP_FULLSCREEN = 2363459;
    /** https://www.google.com:443/accounts/ */
    public static final int URL_GOOGLE_ACCOUNTS = 2365173;
    /** http://jabber.org/protocol/chatstates */
    public static final int XMPP_NS_CHATSTATES = 2430320;
    /** +++JanFebMarAprMayJunJulAugSepOctNovDec */
    public static final int MONTH_ABBREV_TABLE = 2558996;
    /**   %АЁ   «Н         P   j2me Mail.Ru   */
    public static final int MMP_AUTH_PACKET = 2689260;
    /** IssueAuthToken?service=mail&Session=true& */
    public static final int GOOGLE_ISSUE_AUTH_TOKEN = 2692947;
    /** https://api.login.icq.net/auth/clientLogin */
    public static final int URL_ICQ_CLIENT_LOGIN = 2755089;
    /** devId=ic122ravsLx0z-5F&f=xml&idType=ICQ&s= */
    public static final int ICQ_AUTH_PARAMS = 2755131;
    /** http://win.mail.ru/cgi-bin/signup?mobileagent */
    public static final int URL_SIGNUP = 2950249;
    /** &func_name=ajax_get_folder_msg_list_info_part */
    public static final int FUNC_AJAX_GET_FOLDER_LIST = 2950868;
    /**  HTTP/1.1
User-Agent: J2ME MailAgent
Host:  */
    public static final int HTTP_REQUEST_HEADER = 2951238;
    /** http://api.icq.net:5190/aim/startOSCARSession */
    public static final int URL_ICQ_OSCAR_SESSION = 2951781;
    /** data/trackpoints?getPath.aspx?mode=distance&x0= */
    public static final int API_TRACKPOINTS = 3085016;
    /** http://mobile.mail.ru/data/map_point/add_object? */
    public static final int URL_MAP_POINT_ADD = 3150648;
    /**                                              */
    public static final int MMP_CAPS_HEADER = 3213669;
    /**     '                 яя    яя                    */
    public static final int MMP_CAPS_HEADER_2 = 3213718;
    /** http://mobile.mail.ru/data/map_point/view_object? */
    public static final int URL_MAP_POINT_VIEW = 3216135;
    /** 2DBvQWJBam3xuyYyQ0BeYuWKKfpk5fV4Z6sPc9wTBfeTx442f6 */
    public static final int VK_API_SECRET = 3282875;
    /** http://maps.mail.ru/GeoObjectSearchInArea2.aspx... */
    public static final int URL_GEO_SEARCH_ZOOM = 3473998;
    /** http://mra.mail.ru/settings/MobileJMEAgent/sett... */
    public static final int URL_SETTINGS_XML = 3607418;
    /** http://maps.mail.ru/GeoObjectSearchInArea2.aspx... */
    public static final int URL_GEO_OBJECT_SEARCH_2 = 3805583;
    /** ClientAuth?PersistentCookie=false&source=google... */
    public static final int GOOGLE_CLIENT_AUTH = 3807001;
    /**  HTTP/1.1
Accept: image/png
User-Agent: J2ME ... */
    public static final int HTTP_MAP_TILE_HEADER = 3870861;
    /** http://api.icq.net/expressions/get?f=native&typ... */
    public static final int URL_ICQ_BUDDY_ICON = 3998225;
    /** http://api.vkontakte.ru/api.php?api_id=2023699&... */
    public static final int URL_VK_AUTH_GET = 4069357;
    /** a b v g d e zh z i y k l m n o p r s t u f h c ... */
    public static final int TRANSLIT_TABLE_BASIC = 4788096;
    /**   д  д  д  д  д  ... */
    public static final int MMP_TRANSFER_HEADER = 5245205;
    /** http://api.vkontakte.ru/api.php?api_id=2023699&... */
    public static final int URL_VK_AUTH_TOKEN_SECURE = 5249005;
    /** Privet, ia postavil Mobile Mail.ru Agent, dobav... */
    public static final int INVITE_MESSAGE_RU = 5510023;
    /** 
Connection: keep-alive
Cache-Control: no-tra... */
    public static final int HTTP_TILE_HEADERS = 6689002;
    /** <?xml version="1.0"?><stream:stream xmlns:strea... */
    public static final int XML_XMPP_STREAM_HEADER = 8131775;
    /** &buildNumber=1000&clientName=Mail.ru%20J2ME%20A... */
    public static final int ICQ_OSCAR_PARAMS = 11012754;
    /** a b v g d e z i y k l m n o p r s t u f h c " '... */
    public static final int TRANSLIT_TABLE_EXTENDED = 14290598;
    /** eNptUsFugkAQJaYnE/9h0nOji6Kx+g29ND3uBXFBUgSDa3s... */
    public static final int MRIM_MESSAGE_RTF_BLOB = 33819707;
}
